### ISSUE TITLE
Use proper filename for easier userscript install.

### ISSUE THREAD

**Issue by BrockA** [lbotinelly/SOClearChat#3]
The file needs to be named in the pattern: [filename].user.js, so that standard userscript engines can recognize it as an installable userscript.

So, in this case, rename the file to `so-clearchat.user.js`.

Then you can add an install link to [your Stack Apps page](http://stackapps.com/q/7130/7653) with this code:

    To install, click: <kbd>[Install SO Clearchat](https://github.com/lbotinelly/SOClearChat/raw/master/so-clearchat.user.js)</kbd>

See [this page](http://stackapps.com/q/7057/7653) for an example of a handy install button.

**Comment by lbotinelly** [comment]
Had no idea this functionality was available, thanks for pointing that out!

**Comment by lbotinelly** [comment]
Implemented on [commit b3e35379f1de61193a1534f3c04ff7af1fdfd1e9](https://github.com/lbotinelly/SOClearChat/commit/b3e35379f1de61193a1534f3c04ff7af1fdfd1e9).
